### ISSUE TITLE
On a touch device, it is not possible to ungroup or group by drag'n'drop.

### ISSUE THREAD

**Issue by MartinEhg** [jishi/node-sonos-web-controller#38]
could you implement the posibillity to have checkboxes to group or ungroup?
Like it is in the songs app?

**Comment by jishi** [comment]
My standpoint is that I won't try to support touch devices in the desktop UI, but instead have a touch-centric interface that is more similar to the mobile version of the sonos app and try to make that responsive.

I started with that a long time ago (you can check it out on the /m url), but it is still lacking a lot of the features from the regular interface. With that said, having checkboxes (or some other way of grouping multiple players in one go) might still have a need, it would just not be because of touch support. 

What kind of device are you trying to use for this?

**Comment by drohack** [comment]
I have not tried the touch support for the web controller yet (as I'm currently waiting for my screen). But I'm going to be trying to use the Official 7" Raspberry Pi screen with my Raspberry Pi 2 model B as both the host and interface of this web controller and I'd love to see some love for touch support.

**Comment by jishi** [comment]
Touch is supported in the /m layout. Issues should be filed against missing functionality in that layout instead.
