### ISSUE TITLE
Request: Add Volume + and - buttons

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-web-controller#50]
Add buttons for volume up and volume down as the slider can be difficult on some tablets

**Comment by jishi** [comment]
I spent a lot of time making the slider of the mobile layout (`/m`) touch-friendly. The desktop layout is mouse-optimized (supports mousewheel adjustment etc). Then plan was to separate them completely since it would be easier to maintain. A tablet/mobile layout have other challenges as well. Please test the behavior of the mobile layout and tell me what you think.

**Comment by autofrank** [comment]
Thanks - I'll take a look at it and come back

**Comment by autofrank** [comment]
I accessed the controller on a 10" samsung Tab4 to test out the volume control slider and while it works I find it as awkward as the one on the native app. perhaps its the size  but I can't drag the slider but can click in front of the slider to volume up but if the volume is at 30% I can't reduce as there is no room

I'll play with it a but more over the coming days...

**Comment by jishi** [comment]
Are you talking about the slider on the `/m` layout?  because that one isn't supposed to be tapped, and I'm surprised of that works. It is slidable, regardless of where you start, and it is downstepped so you can never adjust more than 25% per slide, deliberately. It should be even easier to control volume than the native Sonos controller one, otherwise I have failed miserably :)
 
Just swipe over the volume rocker, it should work.

**Comment by jishi** [comment]
Are you using the Samsung native browser (is that still a thing?), or Chrome for Android?

**Comment by autofrank** [comment]
I'm using chrome and also tried another tablet with chrome and the same behaviour..
not sure what you mean by the **/m** layout just to make sure we are talking the same language...


![image](https://cloud.githubusercontent.com/assets/20369477/19248293/1170b656-8f27-11e6-83c1-9962745fa5f1.png)

when I touch the grey volume the white one pops up (as if there were multiple zones) 
I am tapping the grey part of this control and can tap up in increments but there isnt enough room ot tap down

is there some other place I should be tapping ?

thanks
-f

**Comment by jishi** [comment]
Okay, makes sense now. When I say, the `/m` layout, I mean the alternative layout if you visit:

`http://[ip of pi]:8080/m`

instead of just `http://[ip of pi]:8080`

There is a lot of stuff that probably doesn't work on a touch-screen with the normal layout, I rely on doubleclick and drag n' drop which is a major pita on touchscreens.

**Comment by jishi** [comment]
Kind of curious what your "PizzaBBQ_Area" is... :D You have your own pizza oven?

**Comment by autofrank** [comment]
ahhh.. I didn't know about the /m layout
It looks like its very early development

![image](https://cloud.githubusercontent.com/assets/20369477/19248744/a32a6392-8f29-11e6-9dd0-bab24457eb38.png)

Is this what I am supposed to be seeing  or is there more ?
Which version do you think you'll be progressing ?

**Comment by jishi** [comment]
You should have seen the cover art to the left. And the volume slide container doesn't seem to fit all your players. But the volume slider behavior should still work.

I probably need to progress both of them, they fulfill different purposes but you are right that the mobile view is more of an early development.

**Comment by autofrank** [comment]
makes sense - I wasn't too sure how to select the players. I can test and provide feedback on either if the time comes. 
I was an early adopter of sonos, bought my first one (ZP100) 10+ years ago and now have 14 now and all are working perfectly. I probably have most models at this stage (except soundbar/sub which I don't think are worth the money) so if you need to test any feature at scale I could help out...

thanks again
-f
